### ISSUE TITLE
Removing script name and file shortcut from bottom of menu.

### ISSUE THREAD

**Issue by ukulanne** [p-e-w/argos#46] opened 2018-05-03 13:45 UTC
Is there a way to remove the last entry with the shortcut to the script that appears at the bottom of the menu? Something like ARGOS_SHOW_SCRIPT. Also something like ARGOS_SHOW_SCRIPT_NAME to be able to change the name of the script shown if it is desired to keep it.

**Comment by teras** [comment] 2018-05-07 08:12
I'd double that, or at lease minimize the screen space that reserves the separator and the filename indicator

**Comment by p-e-w** [comment] 2018-05-12 09:29
Duplicate of #35.

**Closed by p-e-w** 2018-05-12 09:29 UTC
Labels: duplicate
